rm(list=ls())
library(gamlss)
library(tidyverse)
library(ggpubr)
library(skimr)
data('rent')
datos <- rent %>% select(R, Fl, A, H, loc)
datos <- datos %>%setNames(c('valor', 'metros', 'anio', 'calef', 'local'))
head(datos)

mod_OLS <- gamlss( formula = valor ~ metros + anio + calef + local, family = NO, data = datos, trace = FALSE)
summary(mod_OLS)
plot(mod_OLS)
wp(mod_OLS)

mod_GAM_sin_pb <- gamlss( formula = valor ~ metros + anio + calef +local, family = GA, data = datos, trace = FALSE)
summary(mod_GAM_sin_pb)
plot(mod_GAM_sin_pb)
wp(mod_GAM_sin_pb)

mod_GAM_con_pb <- gamlss( formula = valor ~ pb(metros) + pb(anio) + calef +local, family = GA, data = datos, trace = FALSE)
summary(mod_GAM_con_pb)
plot(mod_GAM_con_pb)
par(mfrow = c(1,2))
wp(mod_GAM_sin_pb)
wp(mod_GAM_con_pb)
par(mfrow = c(1,1))

drop1(mod_GAM_con_pb, parallel = 'multicore', ncpus = 6)
term.plot(mod_GAM_con_pb, , pages = 1, ask = FALSE, rug = TRUE)
